/**
 * Server-side renderer for document PDFs, ported from the portal's
 * CleanDocumentPreview so that PDFs generated by the backend (operator/chat
 * bot, public pay page, emailed documents) match what users see and print in
 * the portal.
 *
 * Ported so far: QUOTATION, INVOICE (standard non-Biofuel layout).
 * Every other type returns null and the caller keeps using the legacy generic
 * layout — so nothing regresses while the remaining types are ported one by
 * one (DO, PO/PR, CN/DN, OR, SO, stock adjustments).
 */
import { pageShell } from './shared';
import { renderQuotationBody } from './quotation';
import { renderInvoiceBody } from './invoice';
import { renderIdQuotationBody } from './id-quotation';

/** Interior-design quotation (config.templateVariant 'ID' / config.quote tree). */
const isIdQuotation = (data: any): boolean =>
  String(data?.templateVariant || data?.config?.templateVariant || '').toUpperCase() === 'ID' || !!(data?.quote || data?.config?.quote);

const QUOTATION_TYPES = ['QUOTATION', 'QO', 'QO1', 'QO2', 'QT'];
const INVOICE_TYPES = ['INVOICE', 'TI', 'TI2'];

/** Page margins for ported layouts — matches the portal's print geometry
 *  (@page margin 20mm 15mm) and applies to every page, unlike CSS padding. */
export const PORTED_PDF_MARGIN = { top: '20mm', right: '15mm', bottom: '20mm', left: '15mm' };

export function isPortedType(type: string): boolean {
  const t = String(type || '').toUpperCase();
  return QUOTATION_TYPES.includes(t) || INVOICE_TYPES.includes(t);
}

/**
 * @returns full HTML for the document, or null when this type has no ported
 *          renderer yet (caller should fall back to the legacy layout).
 */
export function renderDocumentHtml(type: string, data: any, organization?: any): string | null {
  const t = String(type || '').toUpperCase();
  if (QUOTATION_TYPES.includes(t)) {
    const org = organization || data?.organization || data?.company || {};
    if (isIdQuotation(data)) {
      return pageShell(renderIdQuotationBody({ ...(data || {}), quote: data?.quote || data?.config?.quote }, org));
    }
    return pageShell(renderQuotationBody(data || {}, org));
  }
  if (INVOICE_TYPES.includes(t)) {
    return pageShell(renderInvoiceBody(data || {}, organization || data?.organization || data?.company || {}));
  }
  return null;
}
