#!/bin/bash

echo "=== AIMS Project Terminal Setup ==="
echo ""
echo "Follow these steps to set up your development environment:"
echo ""
echo "1. In VS Code, press Cmd+Shift+\` to open a new terminal"
echo "2. In the first terminal, run: cd portal-production && npm run dev"
echo "3. Press Cmd+Shift+\` again for a second terminal"
echo "4. In the second terminal, run: cd api-server-production && npm run start:dev"
echo "5. Press Cmd+Shift+\` again for a third terminal"
echo "6. Keep the third terminal in the root folder for git commands"
echo ""
echo "Alternative: Use the shell script for external terminals:"
echo "./open-terminals.sh"
echo ""
echo "VS Code Terminal Shortcuts:"
echo "- Cmd+Shift+\` : New terminal"
echo "- Cmd+Shift+5 : Split terminal horizontally"
echo "- Cmd+Shift+6 : Split terminal vertically"
echo "- Cmd+Shift+[ : Previous terminal"
echo "- Cmd+Shift+] : Next terminal"
echo ""
echo "Press any key to close this guide..."
read -n 1 